### ISSUE TITLE
Twitter handle is not being saved

### ISSUE THREAD

**Issue by furilo** [TrackDons/trackdons#107]
And it seems the saved ones have been lost

**Comment by ferblape** [comment]
It's working in production using both a twitter URL or just the twitter handle (see [Goteo.org](http://trackdons.org/es/projects/goteo-org))

Maybe it stopped working in a branch and not in master?

**Comment by furilo** [comment]
It seems if you write "@goteo", it saves it fine. If then you edit it, the input only shows "goteo", and if you try to save something without the @, it doesn't save it (I just reproduced it in production)
