### ISSUE TITLE
Signup/login modal window

### ISSUE THREAD

**Issue by furilo** [TrackDons/trackdons#112]
Hey, this is a proposal for signup/login modal window. Instead of two screens (one for signup, one for login) I think we can go with this one. 

![image](https://cloud.githubusercontent.com/assets/24740/6523317/0464ce3e-c3ef-11e4-898c-b6c280eef356.png)

If you don't have an account, are signing up with email+pass, and click on "Create account", we would do a transition (inline in the page, so instant change):

![image](https://cloud.githubusercontent.com/assets/24740/6523327/1d39a574-c3ef-11e4-85f4-934b3a174388.png)

For password recovery, I'm not 100% sure, but maybe we could show some hint/link when user focus on password field: 

![image](https://cloud.githubusercontent.com/assets/24740/6523447/2c12f9e6-c3f0-11e4-8b1a-3fb8ffc1b5da.png)

![image](https://cloud.githubusercontent.com/assets/24740/6523462/51969a42-c3f0-11e4-99d6-4ff402a05f85.png)

**Comment by furilo** [comment]
Hey @nobuti I'm going to integrate this. Fine if we use http://codyhouse.co/demo/login-signup-modal-window/index.html#0, or do you another preferred way to do modals?

**Comment by nobuti** [comment]
:+1: It's a really good object. Put it in a separated file though, we want out frontend looks like a framework  ;)

**Comment by nobuti** [comment]
By file, I mean a partial .scss file :)

**Comment by ferblape** [comment]
Do you want to store a hint in the users? It's fine for me!

**Comment by furilo** [comment]
What do you mean @ferblape ?

**Comment by furilo** [comment]
@nobuti yeah, don't worry, I've already looked at your code organization and I'm ready to follow it! ;)

**Comment by ferblape** [comment]
![screen shot 2015-03-09 at 09 40 40](https://cloud.githubusercontent.com/assets/17616/6551941/5f1dab54-c640-11e4-9821-226ac755dbe7.png)


I mean: the link "¿tu password?" is a hint for the users?

**Comment by furilo** [comment]
@ferblape Yeah that would be the way to have them shown the password recovery field. Although maybe we should go with the first/simpler versión?

**Comment by ferblape** [comment]
Yep, +1
