### ISSUE TITLE
Idea for a home page

### ISSUE THREAD

**Issue by furilo** [TrackDons/trackdons#113]
A slightly radical idea for a home page for not-logged-in users. 

![image](https://cloud.githubusercontent.com/assets/24740/6524905/276528ba-c3ff-11e4-9dbd-8083fcfbaaa4.png)

![image](https://cloud.githubusercontent.com/assets/24740/6524909/2e481642-c3ff-11e4-8fa3-f61df69d95b2.png)

![image](https://cloud.githubusercontent.com/assets/24740/6524912/360553cc-c3ff-11e4-9b64-02257e6876db.png)

If NO is answered to the first question: 

![image](https://cloud.githubusercontent.com/assets/24740/6524921/44e13a78-c3ff-11e4-9ca2-711d08ace6a4.png)

(the others would be similar)

Comments?

**Comment by nobuti** [comment]
I like it :)
