### ISSUE TITLE
How to show recurring donations

### ISSUE THREAD

**Issue by furilo** [TrackDons/trackdons#116]
- [ ] **Listing donations**
(I think we already talked about this?) I would show just one entry, showing that it is a recurring donation. Something like this:

![image](https://cloud.githubusercontent.com/assets/24740/6662925/4dc9da04-cbc1-11e4-807c-8cfb70ccca56.png)

Or:

![image](https://cloud.githubusercontent.com/assets/24740/6662863/c09957e0-cbc0-11e4-831d-3fa9bfc1bbd5.png)

(I like this last best; on hover we could display a tooltip further explaining what this means)

Thoughts?

And as we are only showing one entry, I would take the date of when the user created the recurring donation, independently of when it started or when has been the last donation. I asume we can do this without too much complication. 

Also, in the future we can think in a block to show all recurring donations/donators a user/project has, but I wouldn't worry about it now.

- [ ] **Editing a recurring donation**
Now when you click on "Edit" for a donation that belongs to a recurring donation you are only editing that entry, not the recurring donation in itself, which is what I feel we should be doing.

**Comment by ferblape** [comment]
I'd add Stopping a recurring donation.

:+1: to the compact format.

In order to show a single entry of the recurring donation the query should be something like: `current_user.donations.where(recurring_donation_id: nil) + current_user.recurring_donations`, and all of that sorted by date.  It's feasible.

**Comment by furilo** [comment]
@ferblape can you take this and then I adjust styles?

**Comment by ferblape** [comment]
Yes

**Comment by ferblape** [comment]
Released!
