### ISSUE TITLE
Profile page: don't show total amount

### ISSUE THREAD

**Issue by furilo** [TrackDons/trackdons#117]
I'm starting to think that we should focus on the # of donations a user has made, # of projects she is following/thinking on donating to, and don't show the total quantity, as people with different income levels will have different capacity, and we shouldn't worry about the quantity in itself but rather on the intent.

**Comment by furilo** [comment]
(I plan on proposing a design, let me know what you think)

**Comment by ferblape** [comment]
:+1: makes totally sense to me

**Comment by furilo** [comment]
![image](https://cloud.githubusercontent.com/assets/24740/6688581/dad44846-ccb4-11e4-8af9-4ab140dc5cc2.png)

**Comment by ferblape** [comment]
"Wants to don" is donated - followed?

**Comment by furilo** [comment]
Mmmno. As you might have seen in the project page, I'm playing with the concept "Thinking on donating" instead of "Follow" (but I feel we have to improve the UI). So that counter would be the projects you have not yet donated to and marked as "Thinking on donating"

**Comment by furilo** [comment]
I'm also going to remove it from the donation list item to test how it feels.
