### ISSUE TITLE
Project list "sort by" links not working once selected

### ISSUE THREAD

**Issue by bertocq** [TrackDons/trackdons#141]
Once you select a type of sorting "Latest/Alphabetical/Popularity", the other options get the same link as the actual url. The exception is when there is no sort_by parameter on the url and "latest" is used by default.

Steps to reproduce:
1- Visit http://trackdons.org/es/projects/category/technology
2- Select either the "ALFABÉTICO" or "POPULARIDAD" link
3- Verify that now the other two sorting links have the url set to the actual sort_by parameter, making impossible to change the sorting.

**Comment by ferblape** [comment]
Thanks for the repot. I saw a few error notifications right now.

Do you want to try a PR?

**Comment by bertocq** [comment]
Yes, I'm actually installing my fork to give it a try, I'll ask you or @demimismo tomorrow if I get stuck :). Learn by doing FTW!
