### ISSUE TITLE
Can't create new lines with "enter" key while editing a project description textarea

### ISSUE THREAD

**Issue by bertocq** [TrackDons/trackdons#143]
If you submit any form using the enter key on a input you will be redirected to http://trackdons.org/es/donations#modal-track for example at http://trackdons.org/es/invite

Also while editing a project's description (either new or existing) if you try to create a new line in the text with the **"enter"** key (or any variation with Alt, Shift, Control,etc...) instead of the expected behaviour, it launches the "Track Donation" modal window with an aditional error
> "Donation couldn't be created: Cantidad is not a number and Fecha can't be blank"

And even avoiding to render the TrackDon form, it still submits the form without allowing a new line to be created on the textarea

Reproduced with OSX and:
- Google Chrome 41.0.2272.118
- Mozilla Firefox 35.0.1

**Comment by bertocq** [comment]
Done some research and the donation modal form is being rendered at the bottom of every page, and somehow captures the submit event. Maybe it should only be rendered at trackdons.org/es/donations ?

I'm creating another issue (#145) for this because it seems to happen on other forms if you use the enter while on an input, for example at http://trackdons.org/es/invite

Now back to this issue... still left the main problem: prevent the form from being submitted if you hit **enter** while on the description textarea

**Comment by bertocq** [comment]
This will need some review from @ferblape because the problem is fixed if you remove lines 47..54 from app/assets/javascripts/modules/modal.js

```javascript
  // Prevent Enter key to click on the first button of the form, which is the link to the
  // other form
  $(document).keydown(function(event){
    if(event.which=='13'){
      event.preventDefault();
      $('form:visible').submit();
    }
  });
```
Added in the commit f4d468a9556fbaeaf39f876e877a97b97ec95b40

**Comment by nobuti** [comment]
You are right, that event should be bounded only if the modal is open. Once it is closed, it should be remove from the document. Pull request?

**Comment by bertocq** [comment]
Yes you're right too! Too many hours today :D, I didn't really got what was happening there. I'll give it a try tomorrow

**Comment by bertocq** [comment]
I'm a mess, the branch references the duplicated issue, but fixed it on the pull request title&description ^_^. I think it's all right from my testing.
