### ISSUE TITLE
Donation tracking UI improvement

### ISSUE THREAD

**Issue by furilo** [TrackDons/trackdons#67]
Some ideas:

![image](https://cloud.githubusercontent.com/assets/24740/5684186/6517e546-982e-11e4-9717-604e2efdaac5.png)

You can say if its a recurring donation. You can track several at once: 

![image](https://cloud.githubusercontent.com/assets/24740/5684192/6f5890b4-982e-11e4-93a7-d4e0aa6da928.png)

If its a new project / if you say its recurring (we change the "Date" label to "Starting date"): 

![image](https://cloud.githubusercontent.com/assets/24740/5684181/52254834-982e-11e4-94ac-81f7128da137.png)

As you have seen, I omit the textarea for putting the comment. Mainly because I can't make it to fit in ;) And in part because maybe we can ask the user to put the comment as a standalone field after she has created the donation. This also relates to another idea I will share soon...

**Important**

- [ ] Prompt user to tell the story/reasons why she has donated in a second step
- [ ] Start thinking about #88 Reminders

**Comment by nobuti** [comment]
One doubt, the project field, is a select2 element? or just a simple input text field? I think we can go with a lean autocomplete component.

**Comment by furilo** [comment]
Yes, a select2, the same we have now working.

**Comment by furilo** [comment]
A quick sketch of the post-donation page in which we invite the user to comment and set up the reminder. Pending: think what to do when the user saves various donations at once ;) 

![image](https://cloud.githubusercontent.com/assets/24740/6219382/ffd3e270-b628-11e4-8c08-7a36a25d6d41.png)

**Comment by ferblape** [comment]
Should we show all the forms for each project they donated with a big "Skip" link?

**Comment by furilo** [comment]
@ferblape: yes maybe... and we could also include a CTA in donations tracked without comment, so we invite people to add it in any moment...

@nobuti how are you doing with this? need anything from us?

**Comment by nobuti** [comment]
I asked for help to @ferblape in order to integrate the views. I made a demo, but still I need to update the styles because the white space is not same.

**Comment by nobuti** [comment]
Mmm I see now the page project was updated taking this into account. Then, I can go with the post-donation page.

**Comment by furilo** [comment]
I'll close this and open a new one for the post-donation comment textarea.
