### ISSUE TITLE
Add Country to a project

### ISSUE THREAD

**Issue by furilo** [TrackDons/trackdons#92]
Before #34 

This should reflect the geographical scope of a project. Thus, we'll have some projects which are global (ie Wikipedia). We'll also have some that works towards a continent or a sum of countries, but I would leave them aside for the time being -- or maybe let users select various countries?

**Comment by ferblape** [comment]
+:one: to a list of countries, and when the value is nil it's a global project (like Wikipedia)

We can use PostgreSQL array feature to store the list of countries.

**Comment by furilo** [comment]
ok, perfect.

**Comment by ferblape** [comment]
Hey, I'm planning to add a multiple country selector to the projects form. @nobuti should I do it manually with JS or is there any good plugin?

**Comment by furilo** [comment]
Select2 (which we are already using) supports it http://select2.github.io/examples.html

**Comment by nobuti** [comment]
The select2 handle the multiple selection as tags. I'm not a big fan of the select2. Until now we used to use it only for single value, more as autocomplete component. But now it makes more sense to use it. I was developing a leaner alternative, but I leave it for now. I'll tweak a bit the look and feel in #67 then I can apply it here.

**Comment by furilo** [comment]
btw, the decision is completely yours @nobuti ! ;)

**Comment by nobuti** [comment]
:+1:
