### ISSUE TITLE
Add the project to Travis

### ISSUE THREAD

**Issue by ferblape** [TrackDons/trackdons#94]
[Travis](https://travis-ci.org) is a great solution for CI, and I think totally necessary for accepting external PR from our workflow. 

@furilo could you add the project to Travis? I have created the `.travis.yml` file in the root of the project, and the rest should work, because it's pretty standard.

**Comment by furilo** [comment]
Done. What more is needed? Just a commit? https://travis-ci.org/TrackDons/trackdons

**Comment by ferblape** [comment]
Did you setup any hook in the Github repository?

Master branch build is working here:
https://travis-ci.org/TrackDons/trackdons

But now I want to setup a build for each PR opened in the project.

**Comment by furilo** [comment]
mmm... it seems its not needed. Its working:
https://travis-ci.org/TrackDons/trackdons

What I don't know if its automatic its the build indicators in the PRs (but
I can't find any info whatsoever)

On Tue, Feb 10, 2015 at 8:01 AM, Fernando Blat <notifications@github.com>
wrote:

> Did you setup any hook in the Github repository?
>
> Master branch build is working here:
> https://travis-ci.org/TrackDons/trackdons
>
> But now I want to setup a build for each PR opened in the project.
>
> On Mon, Feb 9, 2015 at 9:08 PM, Álvaro Ortiz <notifications@github.com>
> wrote:
>
> > Done. What more is needed? Just a commit?
> > https://travis-ci.org/TrackDons/trackdons
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/TrackDons/trackdons/issues/94#issuecomment-73580297
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TrackDons/trackdons/issues/94#issuecomment-73653606>.
>



-- 
http://www.mumumio.com
http://www.furilo.com

**Comment by ferblape** [comment]
It works! In the PR page, you can see, next to each commit, a circle with the CI status:

![screen shot 2015-02-10 at 20 08 41](https://cloud.githubusercontent.com/assets/17616/6134315/a91a5cc4-b160-11e4-8d7b-fc5b57edd05f.png)

(Of course, only on commits that happened after we integrated Travis)

**Comment by ferblape** [comment]
I think we can close the issue.
